ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1


network={
    ssid="Christians iPhone 13"
    psk="secretpwd"
    key_mgmt=WPA-PSK
}

network={
    ssid="Tegzuz"
    psk="twogirlsonedog"
    key_mgmt=WPA-PSK
}

network={
        ssid="ATTwCweUzn"
        psk="t8y5xmezs?hz"
        key_mgmt=WPA-PSK
}

network={
        ssid="Capital Club"
        psk="1nnovate@CapitalClub!"
        key_mgmt=WPA-PSK
}

network={
        ssid="Tenant 1"
        psk="DRApopup21"
        key_mgmt=WPA-PSK
}

network={
        ssid="raldawgs"
        psk="raldawgginrandos"
        key_mgmt=WPA-PSK
}

network={
        ssid="HomeOwners"
        psk="wolfpack2013"
        key_mgmt=WPA-PSK
}

network={
        ssid="Harris"
        psk="faithbegora"
        key_mgmt=WPA-PSK
}

