steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - addToQueue  # this is the name of the Google Cloud Function
      - --region=us-central1
      - --runtime=python38  # specify version of Python to use
      - --source=./backend  # this is the source directory for the code to be deployed
      - --trigger-http
      - --memory=2Gi

options:
  logging: CLOUD_LOGGING_ONLY
